// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kmmjCtN66rq7SdVtNs-rV-SXLJBl2Yc',
    appId: '1:1022593340174:web:45a1bcc1f9722a2a8b7d5f',
    messagingSenderId: '1022593340174',
    projectId: 'blue-leaf-guide',
    authDomain: 'blue-leaf-guide.firebaseapp.com',
    storageBucket: 'blue-leaf-guide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5DaxePJTZi2zEXyDMXXmw9LP--sX-Mhg',
    appId: '1:1022593340174:android:2b3246b8d0ab18188b7d5f',
    messagingSenderId: '1022593340174',
    projectId: 'blue-leaf-guide',
    storageBucket: 'blue-leaf-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZy1SkoyAUdB3qWSZkUpeNeNe7Xun2Q8c',
    appId: '1:1022593340174:ios:a04b9d98bd3acb338b7d5f',
    messagingSenderId: '1022593340174',
    projectId: 'blue-leaf-guide',
    storageBucket: 'blue-leaf-guide.firebasestorage.app',
    androidClientId:
        '1022593340174-4bjitvft0dn1uppjq5i49nmqrcujfvd9.apps.googleusercontent.com',
    iosClientId:
        '1022593340174-nktal6ccj75jor1fvvubgk8m7h7c9hld.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueLeafGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZy1SkoyAUdB3qWSZkUpeNeNe7Xun2Q8c',
    appId: '1:1022593340174:ios:a04b9d98bd3acb338b7d5f',
    messagingSenderId: '1022593340174',
    projectId: 'blue-leaf-guide',
    storageBucket: 'blue-leaf-guide.firebasestorage.app',
    androidClientId:
        '1022593340174-4bjitvft0dn1uppjq5i49nmqrcujfvd9.apps.googleusercontent.com',
    iosClientId:
        '1022593340174-nktal6ccj75jor1fvvubgk8m7h7c9hld.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueLeafGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1kmmjCtN66rq7SdVtNs-rV-SXLJBl2Yc',
    appId: '1:1022593340174:web:e2853a8bca1549c08b7d5f',
    messagingSenderId: '1022593340174',
    projectId: 'blue-leaf-guide',
    authDomain: 'blue-leaf-guide.firebaseapp.com',
    storageBucket: 'blue-leaf-guide.firebasestorage.app',
  );
}
